version: '3.8'
  
services:
  wordpress:
    env_file:
      - ./.env
    image: wordpress:php8.0
    environment:
      WORDPRESS_DB_HOST: DB_workdb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./.wp:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/themes/sage
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.work-202110__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.work-202110__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.beeclover.pro`)
        - traefik.http.routers.work-202110__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.work-202110__${PROJECT_NAME}.loadbalancer.server.port=80

########################### NETWORKS
networks:
  default:
    external:
      name: DB_work